stages:
  - test

before_script:
  - ln -s /builds /go/src/code.vereign.com
  - cd /go/src/code.vereign.com/${CI_PROJECT_PATH}

lint:
  image: golangci/golangci-lint:v1.44.2
  stage: test
  tags:
    - amd64-docker
  script:
    - golangci-lint --version
    - golangci-lint run

unit tests:
  image: golang:1.17.8
  stage: test
  tags:
    - amd64-docker
  script:
    - go version
    - go test -race ./... -coverprofile=coverage.out
    - go tool cover -func=coverage.out
