// Code generated by counterfeiter. DO NOT EDIT.
package notifyfakes

import (
	"context"
	"sync"

	"gitlab.eclipse.org/eclipse/xfsc/tsa/policy/internal/notify"
	"gitlab.eclipse.org/eclipse/xfsc/tsa/policy/internal/storage"
)

type FakeStorage struct {
	PolicyChangeSubscribersStub        func(context.Context, string, string, string, string) ([]*storage.Subscriber, error)
	policyChangeSubscribersMutex       sync.RWMutex
	policyChangeSubscribersArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	policyChangeSubscribersReturns struct {
		result1 []*storage.Subscriber
		result2 error
	}
	policyChangeSubscribersReturnsOnCall map[int]struct {
		result1 []*storage.Subscriber
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStorage) PolicyChangeSubscribers(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) ([]*storage.Subscriber, error) {
	fake.policyChangeSubscribersMutex.Lock()
	ret, specificReturn := fake.policyChangeSubscribersReturnsOnCall[len(fake.policyChangeSubscribersArgsForCall)]
	fake.policyChangeSubscribersArgsForCall = append(fake.policyChangeSubscribersArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PolicyChangeSubscribersStub
	fakeReturns := fake.policyChangeSubscribersReturns
	fake.recordInvocation("PolicyChangeSubscribers", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.policyChangeSubscribersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) PolicyChangeSubscribersCallCount() int {
	fake.policyChangeSubscribersMutex.RLock()
	defer fake.policyChangeSubscribersMutex.RUnlock()
	return len(fake.policyChangeSubscribersArgsForCall)
}

func (fake *FakeStorage) PolicyChangeSubscribersCalls(stub func(context.Context, string, string, string, string) ([]*storage.Subscriber, error)) {
	fake.policyChangeSubscribersMutex.Lock()
	defer fake.policyChangeSubscribersMutex.Unlock()
	fake.PolicyChangeSubscribersStub = stub
}

func (fake *FakeStorage) PolicyChangeSubscribersArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.policyChangeSubscribersMutex.RLock()
	defer fake.policyChangeSubscribersMutex.RUnlock()
	argsForCall := fake.policyChangeSubscribersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeStorage) PolicyChangeSubscribersReturns(result1 []*storage.Subscriber, result2 error) {
	fake.policyChangeSubscribersMutex.Lock()
	defer fake.policyChangeSubscribersMutex.Unlock()
	fake.PolicyChangeSubscribersStub = nil
	fake.policyChangeSubscribersReturns = struct {
		result1 []*storage.Subscriber
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) PolicyChangeSubscribersReturnsOnCall(i int, result1 []*storage.Subscriber, result2 error) {
	fake.policyChangeSubscribersMutex.Lock()
	defer fake.policyChangeSubscribersMutex.Unlock()
	fake.PolicyChangeSubscribersStub = nil
	if fake.policyChangeSubscribersReturnsOnCall == nil {
		fake.policyChangeSubscribersReturnsOnCall = make(map[int]struct {
			result1 []*storage.Subscriber
			result2 error
		})
	}
	fake.policyChangeSubscribersReturnsOnCall[i] = struct {
		result1 []*storage.Subscriber
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.policyChangeSubscribersMutex.RLock()
	defer fake.policyChangeSubscribersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ notify.Storage = new(FakeStorage)
