openapi: 3.0.3
info:
  title: Policy Service
  description: The policy service exposes HTTP API for executing policies.
  version: "1.0"
servers:
- url: http://localhost:8081
  description: Policy Server
paths:
  /liveness:
    get:
      tags:
      - health
      summary: Liveness health
      operationId: health#Liveness
      responses:
        "200":
          description: OK response.
  /policy/{group}/{policyName}/{version}/evaluation:
    post:
      tags:
      - policy
      summary: Evaluate policy
      description: Evaluate executes a policy with the given 'data' as input.
      operationId: policy#Evaluate
      parameters:
      - name: group
        in: path
        description: Policy group.
        required: true
        schema:
          type: string
          description: Policy group.
          example: example
        example: example
      - name: policyName
        in: path
        description: Policy name.
        required: true
        schema:
          type: string
          description: Policy name.
          example: example
        example: example
      - name: version
        in: path
        description: Policy version.
        required: true
        schema:
          type: string
          description: Policy version.
          example: "1.0"
        example: "1.0"
      requestBody:
        description: Input data passed to the policy execution runtime.
        required: true
        content:
          application/json:
            schema:
              type: string
              description: Input data passed to the policy execution runtime.
              example: Deleniti non nihil dolor aut sed.
              format: binary
            example: Omnis quasi aut consequuntur.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Incidunt unde consequatur voluptas dolorem nisi temporibus.
                format: binary
              example: Tempore minus.
  /policy/{group}/{policyName}/{version}/lock:
    delete:
      tags:
      - policy
      summary: Unlock policy
      description: Unlock a policy so it can be evaluated again.
      operationId: policy#Unlock
      parameters:
      - name: group
        in: path
        description: Policy group.
        required: true
        schema:
          type: string
          description: Policy group.
          example: Dolorem cumque laborum quis nesciunt.
        example: Aut voluptas.
      - name: policyName
        in: path
        description: Policy name.
        required: true
        schema:
          type: string
          description: Policy name.
          example: Sint nam voluptatem ea consequatur similique et.
        example: Non mollitia nesciunt impedit facere.
      - name: version
        in: path
        description: Policy version.
        required: true
        schema:
          type: string
          description: Policy version.
          example: Ut commodi perspiciatis corporis.
        example: Accusamus autem sequi.
      responses:
        "200":
          description: OK response.
    post:
      tags:
      - policy
      summary: Lock policy
      description: Lock a policy so that it cannot be evaluated.
      operationId: policy#Lock
      parameters:
      - name: group
        in: path
        description: Policy group.
        required: true
        schema:
          type: string
          description: Policy group.
          example: Quis quos qui earum velit illum.
        example: Aliquam atque voluptatum ut dolorem.
      - name: policyName
        in: path
        description: Policy name.
        required: true
        schema:
          type: string
          description: Policy name.
          example: Aut facere veniam repudiandae id.
        example: Aut minus alias.
      - name: version
        in: path
        description: Policy version.
        required: true
        schema:
          type: string
          description: Policy version.
          example: At eos facilis molestias in voluptas rem.
        example: Ab accusantium ut ut aliquid sint animi.
      responses:
        "200":
          description: OK response.
  /readiness:
    get:
      tags:
      - health
      summary: Readiness health
      operationId: health#Readiness
      responses:
        "200":
          description: OK response.
components: {}
tags:
- name: health
  description: Health service provides health check endpoints.
- name: policy
  description: Policy Service provides evaluation of policies through Open Policy
    Agent.
