swagger: "2.0"
info:
  title: Policy Service
  description: The policy service exposes HTTP API for executing policies.
  version: ""
host: localhost:8081
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /liveness:
    get:
      tags:
      - health
      summary: Liveness health
      operationId: health#Liveness
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /policy/{group}/{policyName}/{version}/evaluation:
    post:
      tags:
      - policy
      summary: Evaluate policy
      description: Evaluate executes a policy with the given 'data' as input.
      operationId: policy#Evaluate
      parameters:
      - name: group
        in: path
        description: Policy group.
        required: true
        type: string
      - name: policyName
        in: path
        description: Policy name.
        required: true
        type: string
      - name: version
        in: path
        description: Policy version.
        required: true
        type: string
      - name: x-evaluation-id
        in: header
        description: EvaluationID allows overwriting the randomly generated evaluationID
        required: false
        type: string
      - name: any
        in: body
        description: Input data passed to the policy execution runtime.
        required: true
        schema:
          type: string
          format: binary
      responses:
        "200":
          description: OK response.
          schema:
            type: string
            format: binary
      schemes:
      - http
  /policy/{group}/{policyName}/{version}/lock:
    post:
      tags:
      - policy
      summary: Lock policy
      description: Lock a policy so that it cannot be evaluated.
      operationId: policy#Lock
      parameters:
      - name: group
        in: path
        description: Policy group.
        required: true
        type: string
      - name: policyName
        in: path
        description: Policy name.
        required: true
        type: string
      - name: version
        in: path
        description: Policy version.
        required: true
        type: string
      responses:
        "200":
          description: OK response.
      schemes:
      - http
    delete:
      tags:
      - policy
      summary: Unlock policy
      description: Unlock a policy so it can be evaluated again.
      operationId: policy#Unlock
      parameters:
      - name: group
        in: path
        description: Policy group.
        required: true
        type: string
      - name: policyName
        in: path
        description: Policy name.
        required: true
        type: string
      - name: version
        in: path
        description: Policy version.
        required: true
        type: string
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /readiness:
    get:
      tags:
      - health
      summary: Readiness health
      operationId: health#Readiness
      responses:
        "200":
          description: OK response.
      schemes:
      - http
