openapi: 3.0.3
info:
    title: Policy Service
    description: The policy service exposes HTTP API for executing policies.
    version: "1.0"
servers:
    - url: http://localhost:8081
      description: Policy Server
paths:
    /liveness:
        get:
            tags:
                - health
            summary: Liveness health
            operationId: health#Liveness
            responses:
                "200":
                    description: OK response.
    /policy/{group}/{policyName}/{version}/evaluation:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#1
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: example
                  example: example
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: example
                  example: example
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: "1.0"
                  example: "1.0"
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: EvaluationID allows overwriting the randomly generated evaluationID
                    example: did:web:example.com
                  example: did:web:example.com
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Policy result cache TTL in seconds
                    example: 60
                    format: int64
                  example: 60
            requestBody:
                description: Input data passed to the policy execution runtime.
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Input data passed to the policy execution runtime.
                            example: Aliquam atque voluptatum ut dolorem.
                            format: binary
                        example: Sint nam voluptatem ea consequatur similique et.
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            required: true
                            schema:
                                type: string
                                description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                                example: Non mollitia nesciunt impedit facere.
                            example: Accusamus autem sequi.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Arbitrary JSON response.
                                example: Aut facere veniam repudiandae id.
                                format: binary
                            example: Et nulla.
        post:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#2
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: example
                  example: example
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: example
                  example: example
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: "1.0"
                  example: "1.0"
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: EvaluationID allows overwriting the randomly generated evaluationID
                    example: did:web:example.com
                  example: did:web:example.com
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Policy result cache TTL in seconds
                    example: 60
                    format: int64
                  example: 60
            requestBody:
                description: Input data passed to the policy execution runtime.
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Input data passed to the policy execution runtime.
                            example: Aliquam atque voluptatum ut dolorem.
                            format: binary
                        example: In quis nesciunt autem et.
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            required: true
                            schema:
                                type: string
                                description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                                example: Sunt in et quia cum.
                            example: Qui non quia.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Arbitrary JSON response.
                                example: Aut facere veniam repudiandae id.
                                format: binary
                            example: Error maxime quasi quia non voluptatibus error.
    /policy/{group}/{policyName}/{version}/evaluation/did.json:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: example
                  example: example
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: example
                  example: example
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: "1.0"
                  example: "1.0"
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: EvaluationID allows overwriting the randomly generated evaluationID
                    example: did:web:example.com
                  example: did:web:example.com
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Policy result cache TTL in seconds
                    example: 60
                    format: int64
                  example: 60
            requestBody:
                description: Input data passed to the policy execution runtime.
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Input data passed to the policy execution runtime.
                            example: Aliquam atque voluptatum ut dolorem.
                            format: binary
                        example: Aut minus alias.
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            required: true
                            schema:
                                type: string
                                description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                                example: At eos facilis molestias in voluptas rem.
                            example: Dolorem cumque laborum quis nesciunt.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Arbitrary JSON response.
                                example: Aut facere veniam repudiandae id.
                                format: binary
                            example: Aut voluptas.
    /policy/{group}/{policyName}/{version}/lock:
        delete:
            tags:
                - policy
            summary: Unlock policy
            description: Unlock a policy so it can be evaluated again.
            operationId: policy#Unlock
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: Voluptas ad corporis adipisci inventore ipsum.
                  example: Recusandae dolorum nisi distinctio vitae ad.
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: Perspiciatis voluptatem.
                  example: Corporis est rem.
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: Totam officia necessitatibus tempore nulla animi.
                  example: Consequatur vel rerum rem ipsam nam.
            responses:
                "200":
                    description: OK response.
        post:
            tags:
                - policy
            summary: Lock policy
            description: Lock a policy so that it cannot be evaluated.
            operationId: policy#Lock
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  schema:
                    type: string
                    description: Policy group.
                    example: Optio quia et laborum.
                  example: In libero perspiciatis voluptatum ut soluta.
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  schema:
                    type: string
                    description: Policy name.
                    example: Ut amet.
                  example: Accusamus enim.
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  schema:
                    type: string
                    description: Policy version.
                    example: Recusandae est rerum corrupti quia.
                  example: Quam dolores architecto itaque.
            responses:
                "200":
                    description: OK response.
    /readiness:
        get:
            tags:
                - health
            summary: Readiness health
            operationId: health#Readiness
            responses:
                "200":
                    description: OK response.
components: {}
tags:
    - name: health
      description: Health service provides health check endpoints.
    - name: policy
      description: Policy Service provides evaluation of policies through Open Policy Agent.
