swagger: "2.0"
info:
    title: Policy Service
    description: The policy service exposes HTTP API for executing policies.
    version: ""
host: localhost:8081
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /liveness:
        get:
            tags:
                - health
            summary: Liveness health
            operationId: health#Liveness
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /policy/{group}/{policyName}/{version}/evaluation:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#1
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  required: false
                  type: string
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  required: false
                  type: integer
                - name: any
                  in: body
                  description: Input data passed to the policy execution runtime.
                  required: true
                  schema:
                    type: string
                    format: binary
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            type: string
            schemes:
                - http
        post:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate#2
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  required: false
                  type: string
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  required: false
                  type: integer
                - name: any
                  in: body
                  description: Input data passed to the policy execution runtime.
                  required: true
                  schema:
                    type: string
                    format: binary
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            type: string
            schemes:
                - http
    /policy/{group}/{policyName}/{version}/evaluation/did.json:
        get:
            tags:
                - policy
            summary: Evaluate policy
            description: Evaluate executes a policy with the given 'data' as input.
            operationId: policy#Evaluate
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
                - name: x-evaluation-id
                  in: header
                  description: EvaluationID allows overwriting the randomly generated evaluationID
                  required: false
                  type: string
                - name: x-cache-ttl
                  in: header
                  description: Policy result cache TTL in seconds
                  required: false
                  type: integer
                - name: any
                  in: body
                  description: Input data passed to the policy execution runtime.
                  required: true
                  schema:
                    type: string
                    format: binary
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: binary
                    headers:
                        ETag:
                            description: ETag contains unique identifier of the policy evaluation and can be used to later retrieve the results from Cache.
                            type: string
            schemes:
                - http
    /policy/{group}/{policyName}/{version}/lock:
        post:
            tags:
                - policy
            summary: Lock policy
            description: Lock a policy so that it cannot be evaluated.
            operationId: policy#Lock
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
        delete:
            tags:
                - policy
            summary: Unlock policy
            description: Unlock a policy so it can be evaluated again.
            operationId: policy#Unlock
            parameters:
                - name: group
                  in: path
                  description: Policy group.
                  required: true
                  type: string
                - name: policyName
                  in: path
                  description: Policy name.
                  required: true
                  type: string
                - name: version
                  in: path
                  description: Policy version.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /readiness:
        get:
            tags:
                - health
            summary: Readiness health
            operationId: health#Readiness
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /v1/policies:
        get:
            tags:
                - policy
            summary: ListPolicies policy
            description: List policies from storage with optional filters.
            operationId: policy#ListPolicies
            parameters:
                - name: locked
                  in: query
                  description: Filter to return locked/unlocked policies (optional).
                  required: false
                  type: boolean
                - name: rego
                  in: query
                  description: Include policy source code in results (optional).
                  required: false
                  type: boolean
                - name: data
                  in: query
                  description: 'Include policy static data in results (optional). '
                  required: false
                  type: boolean
                - name: dataConfig
                  in: query
                  description: Include static data config (optional).
                  required: false
                  type: boolean
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PolicyListPoliciesResponseBody'
                        required:
                            - policies
            schemes:
                - http
definitions:
    PolicyListPoliciesResponseBody:
        title: PolicyListPoliciesResponseBody
        type: object
        properties:
            policies:
                type: array
                items:
                    $ref: '#/definitions/PolicyResponseBody'
                description: JSON array of policies.
                example:
                    - data: Commodi nemo fugiat id praesentium accusantium expedita.
                      dataConfig: Qui non quia.
                      group: Sequi adipisci et nulla.
                      lastUpdate: 8181859392515170659
                      locked: false
                      policyName: Consequatur accusamus.
                      rego: Sunt in et quia cum.
                      version: In quis nesciunt autem et.
                    - data: Commodi nemo fugiat id praesentium accusantium expedita.
                      dataConfig: Qui non quia.
                      group: Sequi adipisci et nulla.
                      lastUpdate: 8181859392515170659
                      locked: false
                      policyName: Consequatur accusamus.
                      rego: Sunt in et quia cum.
                      version: In quis nesciunt autem et.
                    - data: Commodi nemo fugiat id praesentium accusantium expedita.
                      dataConfig: Qui non quia.
                      group: Sequi adipisci et nulla.
                      lastUpdate: 8181859392515170659
                      locked: false
                      policyName: Consequatur accusamus.
                      rego: Sunt in et quia cum.
                      version: In quis nesciunt autem et.
        example:
            policies:
                - data: Commodi nemo fugiat id praesentium accusantium expedita.
                  dataConfig: Qui non quia.
                  group: Sequi adipisci et nulla.
                  lastUpdate: 8181859392515170659
                  locked: false
                  policyName: Consequatur accusamus.
                  rego: Sunt in et quia cum.
                  version: In quis nesciunt autem et.
                - data: Commodi nemo fugiat id praesentium accusantium expedita.
                  dataConfig: Qui non quia.
                  group: Sequi adipisci et nulla.
                  lastUpdate: 8181859392515170659
                  locked: false
                  policyName: Consequatur accusamus.
                  rego: Sunt in et quia cum.
                  version: In quis nesciunt autem et.
                - data: Commodi nemo fugiat id praesentium accusantium expedita.
                  dataConfig: Qui non quia.
                  group: Sequi adipisci et nulla.
                  lastUpdate: 8181859392515170659
                  locked: false
                  policyName: Consequatur accusamus.
                  rego: Sunt in et quia cum.
                  version: In quis nesciunt autem et.
                - data: Commodi nemo fugiat id praesentium accusantium expedita.
                  dataConfig: Qui non quia.
                  group: Sequi adipisci et nulla.
                  lastUpdate: 8181859392515170659
                  locked: false
                  policyName: Consequatur accusamus.
                  rego: Sunt in et quia cum.
                  version: In quis nesciunt autem et.
        required:
            - policies
    PolicyResponseBody:
        title: PolicyResponseBody
        type: object
        properties:
            data:
                type: string
                description: Policy static data.
                example: Accusamus enim.
            dataConfig:
                type: string
                description: Policy static data optional configuration.
                example: Recusandae est rerum corrupti quia.
            group:
                type: string
                description: Policy group.
                example: Optio quia et laborum.
            lastUpdate:
                type: integer
                description: Last update (Unix timestamp).
                example: 1029654258457164464
                format: int64
            locked:
                type: boolean
                description: Locked specifies if the policy is locked or allowed to execute.
                example: true
            policyName:
                type: string
                description: Policy name.
                example: Quia non voluptatibus error.
            rego:
                type: string
                description: Policy rego source code.
                example: Ut amet.
            version:
                type: string
                description: Policy version.
                example: In libero perspiciatis voluptatum ut soluta.
        example:
            data: Totam officia necessitatibus tempore nulla animi.
            dataConfig: Consequatur vel rerum rem ipsam nam.
            group: Adipisci inventore ipsum voluptatibus recusandae.
            lastUpdate: 1724369781608544610
            locked: true
            policyName: Architecto itaque voluptatum voluptas ad.
            rego: Ab perspiciatis voluptatem pariatur corporis est rem.
            version: Nisi distinctio vitae.
        required:
            - group
            - policyName
            - version
            - locked
            - lastUpdate
