swagger: "2.0"
info:
  title: Policy Service
  description: The policy service exposes HTTP API for executing policies.
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /liveness:
    get:
      tags:
      - health
      summary: Liveness health
      operationId: health#Liveness
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /readiness:
    get:
      tags:
      - health
      summary: Readiness health
      operationId: health#Readiness
      responses:
        "200":
          description: OK response.
      schemes:
      - http
